### ISSUE TITLE
Is this swift version available on cocoapod

### ISSUE THREAD

**Issue by r-a-o** [bzsinger/REFrostedViewControllerSwiftExample#1]
Is this swift implementation available on cocoapods? If yes, what is the pod name I need to include?

I see that the library is using `REFrostedViewController` pod, which is the objc implementation, so I am not sure if this is a complete rewrite of the original REFrostedViewController or just a wrapper written in swift. Please clarify on this.

PS: It would help to include usage and installation in the README. 
Thanks!

**Comment by bzsinger** [comment]
Thanks for reaching out! 

This isn't the Swift implementation of the CocoaPod – it's an example implementation of the original REFrostedViewController. I found it difficult to understand the [provided examples](https://github.com/romaonthego/REFrostedViewController/tree/master/Examples) in the REFrostedViewController project, so I created an example in Swift 3.

**Comment by r-a-o** [comment]
Thanks @bzsinger 
This helped me integrate REFrostedViewController quicker into my swift project.

**Comment by bzsinger** [comment]
Awesome! Happy to help!
